spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5


data-source:
  ldap1:
    base: dc=example,dc=com
    username: cn=Directory Manager
    password: password
    urls: ldap://opendj.example.com:1389
  ldap2:
    base: dc=example,dc=com
    username: cn=Directory Manager
    password: password
    urls: ldap://opendj.example.com:2389